import rawImages from "@/data/hero-images.json";

export type HeroImage = {
  query: string;
  id: string;
  url: string;
  alt: string;
  width: number;
  height: number;
  color: string;
  photographerName: string;
  photographerUrl: string;
  unsplashUrl: string;
};

export type HeroImageSlot = "hero" | "student" | "landlord" | "agent";

// src/data/hero-images.json is generated by `npm run fetch:images` (see
// scripts/fetch-unsplash-images.mjs). Slots are null until that script has
// been run at least once — components must handle the null case.
const images = rawImages as Record<HeroImageSlot, HeroImage | null>;

export function getHeroImage(slot: HeroImageSlot): HeroImage | null {
  return images[slot];
}
